### ISSUE TITLE
Fixed place for words

### ISSUE THREAD

**Issue by okravchuk** [wvengen/d3-wordcloud#6]
Every new chart render brings new placement of words inside a chart.
How to get the same look of chart from render to render with the same text?

**Comment by wvengen** [comment]
There is a random factor inherent in word clouds. Could you seed the random number generator? (Not sure if that's possible with Javascript.) Otherwise, this belongs in [`d3.layout.cloud`](https://github.com/jasondavies/d3-cloud).
