### ISSUE TITLE
For Android

### ISSUE THREAD

**Issue by AndroidOutThere** [wvengen/d3-wordcloud#8]
This is great work!

For Android, loading html with cloud generation is slower as it runs javascript.
Are there any points where this algorithm can be optimised ? or something can be skipped ? so that its faster.
Or is there any solution you have without javascript (in pure java or for Android)?

Thanks.

**Comment by wvengen** [comment]
I suppose there are Android libraries. Go search for _android word cloud java_, e.g. [this](https://github.com/alhazmy13/AndroidWordCloud) turns up.
